services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin@database:5432/study_planner_db
      ALGORITHM: HS256
      SECRET_KEY: 1234567890qwertyuiopasdfghjklzxcvbnm
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: study_planner_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database_data:
